M48
; DRILL file KiCad 10.0.3 date 2026-06-24T20:29:48
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-24T20:29:48-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X5.275Y-2.7165
X5.315Y-2.5165
X5.355Y-2.7165
T2
X5.0236Y-2.6476
X5.0236Y-2.8248
T3
X5.2756Y-2.3622
X5.2756Y-3.1102
M30
